name: Linux

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_VERBOSE: true

jobs:
  Test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust_toolchain: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_toolchain }}
        override: true

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace

  DeployMasterDoc:
    runs-on: ubuntu-18.04
    container:
      image: rustops/crates-build-env:latest
      options: --memory 3221225472
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    # TODO:
    # * restrict network access during building docs.
    # * restrict all write access expect target/
    - name: Build API docs
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps

    - run: rm -fv target/doc/.lock

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: published-docs
        path: target/doc

    - name: Deply to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc
